spring:
  application:
    name: newsletter-batch-tasklet
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

newsletter:
  recipients: akashpillai1601@gmail.com,chandranrakash@gmail.com